home/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, re_path
from .views import *
app_name = 'home'
urlpatterns = [
    path('', hom, name="hom"),    
    path('addR/', addR, name="addR"),
    path('addST/', addST),
    path('addT/', addT, name="addT"),
    path('addRT/', addRT),  
    re_path(r'^search$', search, name="search"),    
    re_path(r'^pnr$', pnr, name="pnr"),
    re_path(r'^search/trains$', getTrains),    
    path('search/trains/cva/', cva),    
    re_path(r'^search/book1$', book1, name="book1"),  
    re_path(r'^search/book1/book$', book),       
    re_path(r'^schedule$', schedule),        
    path('schedule/trains/', getTinfo),
    re_path(r'^cancel$', cancel, name="cancel"),

    path('cancel/cancel/cn/', cn),
]

rail/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include
from django.urls import re_path as url
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns =[
    url(r'^admin/', admin.site.urls),
    url(r'^login',user_views.login_request, name = 'login'),
    url(r'^register/', user_views.register, name="register"),
    url(r'^logout', user_views.logout_request, name="logout"),
    path('', include('home.urls')), 
]
'''
urlpatterns = [
    path('admin/', admin.site.urls),    
    path('login', user_views.login_request, name='login'),
    path('register', user_views.register, name="register"),
    path('logout', user_views.logout_request, name="logout"),
    path('home/logout', user_views.logout_request, name="logout"),
    # path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('home.urls')),   
] 
'''
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.
class Trains(models.Model):
    tno=models.CharField(primary_key=True,max_length=50)
    tname=models.CharField(max_length=50)
    rid=models.ForeignKey('Route',on_delete=models.CASCADE)

    def __str__(self):
        return self.tno

class Route(models.Model):
    rid=models.CharField(max_length=50)
    ostation=models.CharField(max_length=50)
    dstation=models.CharField(max_length=50)
    def __str__(self):
        return self.rid

class Station(models.Model):
    sid=models.CharField(primary_key=True,max_length=50)
    sname=models.CharField(max_length=50)
    def __str__(self):
        return self.sid


class RouteStation(models.Model):
    tno=models.ForeignKey('Trains',on_delete=models.CASCADE)
    sid=models.ForeignKey('Station',on_delete=models.CASCADE)
    rid=models.ForeignKey('Route',on_delete=models.CASCADE)
    order=models.IntegerField()
    atime=models.CharField(max_length=50)

class Reservation(models.Model):
    tno=models.ForeignKey('Trains',on_delete=models.CASCADE)
    user=models.CharField(max_length=50)
    nos=models.IntegerField()
    date=models.CharField(max_length=50)
    amt=models.IntegerField()
    cls=models.CharField(max_length=50)
    status=models.CharField(max_length=50)
    pnr=models.CharField(max_length=50)
    src=models.CharField(max_length=50)
    des=models.CharField(max_length=50)




class Payment(models.Model):
    pnr=models.CharField(max_length=50)
    user=models.CharField(max_length=50)
    amt=models.IntegerField()
    mtd=models.CharField(max_length=50)
    date=models.CharField(max_length=50)
    cancel=models.CharField(max_length=50)

home/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class Usearch(forms.Form):
    src = forms.CharField(max_length=50)
    des = forms.CharField(max_length=50)

class Trsc (forms.Form):
    tnum=forms.IntegerField()

class AddR(forms.Form):
    rid=forms.CharField(max_length=50)
    ostation=forms.CharField(max_length=50)
    dstation=forms.CharField(max_length=50)

class AddST(forms.Form):
    sid=forms.CharField(max_length=50)
    sname=forms.CharField(max_length=50)

class AddT(forms.Form):
    rid=forms.CharField(max_length=50)
    tno=forms.CharField(max_length=50)
    tname=forms.CharField(max_length=50)

class AddRT(forms.Form):
    tno=forms.CharField(max_length=50)
    sid= forms.CharField(max_length=50)
    rid=forms.CharField(max_length=50)
    order=forms.IntegerField()
    atime=forms.CharField(max_length=50)

class Pnr(forms.Form):
    pnr=forms.CharField(max_length=50)

class Book(forms.Form):
    cls=forms.CharField(max_length=10)
    dt=forms.CharField(max_length=10)

home/views.py
from django.contrib import messages, auth
from django.contrib.auth import authenticate, login
from django.db.models import Max
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.shortcuts import render
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from .models import *
from .forms import Trsc, Usearch, AddR, AddST, AddT, AddRT
from users.models import *
import json

# Create your views here.


def hom(request):
    # return HttpResponse('from home.views.home') ## ok
    return render(request, 'home/index.html')

def search(request):
    print('ln 22 in views.search')
    a = Station.objects.all()
    print('ln 24 a: ', a)
    return render(request, 'home/seat.html', {'a': a})

@csrf_exempt
def getTrains(request):
    print('ln 29 from views.getTrains')
   
    if request.method == 'POST':
        form = Usearch(request.POST)
        if form.is_valid():
            print('ln 33 url search/trains views.getTrains.POST.form valid')
            data = form.cleaned_data
            print('ln 35 data: ', data)
            src = data['src']
            des = data['des']
            print('ln 38 src: ', src, ' des: ', des)
            srcstn = Station.objects.get(sid=src).sname
            print('ln 41 srcstn ', srcstn)
            desstn = Station.objects.get(sid=des).sname
            print('ln 43 desstn ', desstn)
            a = RouteStation.objects.filter(sid=des)
            x = []
            o = 0
            for i in a:
                tno = i.tno
                b = RouteStation.objects.filter(tno=tno, sid=src)
                for j in b:
                    if j.order < i.order:
                        x.append(j)
                        o = i.order-j.order
        else:
            return HttpResponse('<h1>invalid Data</h1>')
        return render(request, 'home/trains.html', {'data': x, 'o': o, 'src': src, 'des': des, 'srcstn': srcstn, 'desstn': desstn})
    return render(request, 'home/pnr.html')
    # return HttpResponse('<h1>Wrong REq</h1>')


def schedule(request):
    a = Trains.objects.all()
    return render(request, 'home/schedule.html', {'a': a})


def getTinfo(request):
    form = Trsc(request.GET)
    if form.is_valid():
        data = form.cleaned_data
        tno = data['tnum']
        a = RouteStation.objects.filter(tno=tno).order_by('order')

        return render(request, 'home/trinfo.html', {'data': a})

    return render(request, 'home/trinfo.html')
    #return HttpResponse('<h1>DAta invalid<h1>')

@csrf_exempt
def addR(request):
    if request.method == 'POST':
        form = AddR(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            a = Route()
            a.rid = data['rid']
            a.ostation = data['ostation']
            a.dstation = data['dstation']
            a.save()
            return redirect('/home/addR')
        else:
            return HttpResponse('<h1>Invalid Data</h1>')

    a = Station.objects.all()

    return render(request, 'home/addR.html', {'stn': a})

@csrf_exempt
def addST(request):
    if request.method == 'POST':
        form = AddST(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            a = Station()
            a.sid = data['sid']
            a.sname = data['sname']
            a.save()
            return redirect('/home/addST')
        else:
            return HttpResponse('<h1>Invalid Data</h1>')

    return render(request, 'home/addST.html')

@csrf_exempt
def addT(request):
    if request.method == 'POST':
        form = AddT(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            a = Trains()
            a.tno = data['tno']
            a.tname = data['tname']
            r1 = Route.objects.get(rid=data['rid'])
            a.rid = r1
            a.save()
            return redirect('/home/addT')
        else:
            return HttpResponse('<h1>Invalid Data</h1>')

    a = Route.objects.all()

    return render(request, 'home/addT.html', {'tr': a})

@csrf_exempt
def addRT(request):
    if request.method == 'POST':
        form = AddRT(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            a = RouteStation()
            t1 = Trains.objects.get(tno=data['tno'])
            a.tno = t1
            s1 = Station.objects.get(sid=data['sid'])
            a.sid = s1
            r1 = Route.objects.get(rid=data['rid'])
            a.rid = r1
            a.order = data['order']
            a.atime = data['atime']
            a.save()
            return redirect('/home/addRT')
        else:
            return HttpResponse(form.errors)

    a = Route.objects.all()
    b = Trains.objects.all()
    c = Station.objects.all
    return render(request, 'home/addRT.html', {'rt': a, 'tr': b, 'st': c})

@csrf_exempt
def cva(request):
    if request.method == 'POST':
        tn1 = request.POST['tno']
        o = int(request.POST['od'])
        cls = request.POST['cls']
        p = 0
        if cls == 'AC':
            p = 120*o
        if cls == 'SL':
            p = 80*o
        if cls == '3A':
            p = 100*o
        if cls == '2S':
            p = 50*o
        dt = request.POST['dt']
        c = 0
        a = Reservation.objects.filter(tno=tn1, cls=cls, date=dt)

        for i in a:
            c = c+i.nos
        if c > 30:
            x = "Waiting-"+str(c-30)
            data = json.dumps({
                'read': x,
                'price': p,
            })
            return HttpResponse(data, content_type='application/json')
        else:
            x = "Available-"+str(30-c)
            data = json.dumps({
                'read': x,
                'price': p,
            })
            return HttpResponse(data, content_type='application/json')
    return render(request, 'home/pnr.html')  # check whether ok

@csrf_exempt    
def book1(request):
    if (request.method == 'POST'):
        dt = request.POST['date']
        src = request.POST['src']
        des = request.POST['des']
        tno = request.POST['bk']
        cls = request.POST['cls'+str(tno)]
        nos = request.POST['nos'+str(tno)]
        pr = request.POST['price'+str(tno)]
        print('ln 197 type of pr: ', type(pr), 'pr: ', pr)
        try:
            int(pr)
        except:
            print('Can not convert', pr ,"to int")
        tname = Trains.objects.get(tno=tno).tname
        return render(request, 'home/payment.html', {'price': int(pr)*int(nos), 'dt': dt, 'cls': cls, 'tno': tno, 'nos': nos, 'tname': tname, 'src': src, 'des': des})
    return render(request, 'home/payment.html')

@csrf_exempt
def book(request):
    if request.method == 'POST':
        nos = int(request.POST['nos'])
        tno = request.POST['tno']
        dt = request.POST['date']
        tn1 = Trains.objects.get(tno=tno)
        cls = request.POST['cls']
        op = request.POST['select']
        tname = request.POST['tname']
        src = request.POST['src']
        des = request.POST['des']
        price = int(request.POST['price'])
        pp = price/nos
        mtd = 'Paytm'
        if op == 'option1':
            crd = request.POST['crd']
            nam = request.POST['nam']
            cvv = request.POST['cvv']
            exp = request.POST['exp']
            mtd = 'Credit/Debit Card'
            if len(crd) != 16 or len(cvv) != 3:
                return render(request, 'home/nopay.html')

        c = 0
        f = 0
        pay = Payment()
        pay.user = request.user
        pay.amt = price
        pay.date = dt
        pay.mtd = mtd
        pay.cancel = 'NO'

        a = Reservation.objects.filter(tno=tno, cls=cls, date=dt)
        c1 = Reservation.objects.all()
        cp = 0
        for i in c1:
            cp = max(cp, int(i.pnr))
        for i in a:
            c = c + i.nos
        if c < 30:
            if nos > (30-c):
                b = Reservation()
                b.cls = cls
                b.tno = tn1
                b.status = "C"
                b.nos = 30-c
                b.amt = 200
                b.date = dt
                b.user = request.user
                b.pnr = cp+1
                b.src = src
                b.des = des
                b.save()
                e = Reservation()
                e.cls = cls
                e.tno = tn1
                e.status = "W"
                e.nos = nos-(30 - c)
                e.amt = price
                e.date = dt
                e.user = request.user
                e.pnr = cp + 1
                e.src = src
                e.des = des
                e.save()
                f = 1
            else:
                b = Reservation()
                b.cls = cls
                b.tno = tn1
                b.status = "C"
                b.nos = nos
                b.amt = price
                b.date = dt
                b.user = request.user
                b.pnr = cp + 1
                b.src = src
                b.des = des
                b.save()
                f = 1
        else:
            b = Reservation()
            b.cls = cls
            b.tno = tn1
            b.status = "W"
            b.nos = nos
            b.amt = price
            b.date = dt
            b.user = request.user
            b.pnr = cp + 1
            b.save()
            f = 2
        c = 0
        a = Reservation.objects.filter(tno=tno, cls=cls, date=dt)
        for i in a:
            c = c + i.nos

        pay.pnr = cp+1
        pay.save()
        return render(request, "home/final.html", {'tname': tname, 'tno': tno, 'date': dt, 'src': src, 'des': des, 'cls': cls, 'pnr': (cp+1), 'nos': nos, 'dt': dt})
    return render(request, "home/final.html")

def cancel(request):
    a = Reservation.objects.filter(user=request.user).values(
        'pnr', 'date', 'tno', 'src', 'des', 'cls', 'nos').distinct()
    return render(request, 'home/cancel.html', {'res': a})

@csrf_exempt
def cn(request):

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Railway System</title>
         <!-- Latest compiled and minified CSS -->
    {% load static %}
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
  
    <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{%static 'js/jquery-3.3.1.min.js'%}"></script>

    <style>
        body{
            background-image:url('{% static "images/hompage.jpg"%}');
            background-size:100%;
            background-repeat:no-repeat;
        }
        .sty
        {
            font-family: 'Dancing Script', cursive;
            color:yellow;
            align-items: center;
        }
        .row1{
            background-color:rgba(0,0,0,0.6);
        }
    </style>
</head>
<body>
    {% include './navbar.html' %}
   
    <br><br><br><br><br><br>
   
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endif %}

        
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </main>  
   
</body>
</html>

home/templates/home/cancel.html
{% extends './srbase.html' %}
{% block body %}
    <h1 style="text-align:center;font-family:sans-seriff; color: yellow;">Current Reservations</h1>
    <h3 style="color:yellow;">from cancel.html</h3>
        {%csrf_token%}
    <div class="container">
    {% for i in res %}
        <div class="tick" style="font-size:13px;color:white;padding:18px;padding-left:40px;">

            &nbsp&nbspDate       :{{i.date}}<br/>
            &nbsp&nbspTrain no   :{{i.tno}}<br/>
            &nbsp&nbspPNR        :{{i.pnr}}<br/>
            &nbsp&nbspSrc        :{{i.src}}<br/>
            &nbsp&nbspDes        :{{i.des}}<br/>
                            <button class="btn btn-danger" value="{{i.pnr}}" style="float:right;border-radius:50%;" onclick="y(this.value)"type="submit">Cancel</button><br/>

        </div>
            <br/><br/>
        {%endfor%}

</div>

     <script>
     function y(vl)
    {



        $.ajax({
            type:'POST',
            url:'home/cancel/cn/',
            data:{
                    id:vl,
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()

                  },
        success:function(data){

            alert("Cancelled Tickets||Amount Refunded:"+data);
            window.location.href=window.location.href;
                               }
            }
                )

    }
    </script>
{%endblock%}

home/templates/home/final copy.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ticket Details</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        .det
        {
            background-color:rgba(0,0,0,0.7);
            color:white;
            }

         body
         {
         background-image:url('{% static "images/comp.jpg"%}');
         background-size:100% 100%;
         height:650px;
         background-repeat:no-repeat;
         }

    </style>
</head>
<body>
<h1 style="text-align:center;font-family:sans-seriff;">Tickets Booked</h1>
<div class="container">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4 det">
    <h3>Ticket Details</h3>
    Train Name   :<b>{{tname}}</b><br/>
    Train No     :<b>{{tno}}</b><br/>
    PNR          :<b>{{pnr}}</b><br/>
    No of seats  :<b>{{nos}}</b><br/>
    Booking Class:<b>{{cls}}</b><br/>
    Booking Date :<b>{{dt}}</b><br/>

    <h4>For Further Enquiry Check PNR</h4>
    <a href="{%url 'home:hom'%}"><button class="btn btn-success">Back To Homepage</button></a>
    <a href="{%url 'home:pnr'%}"><button class="btn btn-info">Check PNR</button></a>
    </div>

    </div>
    </div>

</body>
</html>

home/templates/home/home.html
{% extends './base.html' %}

{% block body %}
<h3 style="color:yellow;">from home.html</h3>
        
{% include './messages.html' %}
  
{% endblock %}

home/templates/home/messages.html
{% for message in messages %}

	<div class="container-fluid mx-0 p-0 sticky-top">
	  	<div class="alert {{ message.tags }} alert-dismissible m-0 p-3" role="alert">
		    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    	<span aria-hidden="true">&times;</span>
		    </button>
	    	{{ message }}
	  	</div>
	</div>

{% endfor %}

home/templates/home/nopay copy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    Tickets Cannot be Booked
    Payment Failed
</body>
</html>

home/templates/home/payment copy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        body
        {
            height:650px;
           background-image:url('{% static "images/pay.jpg"%}');
           background-repeat:no-repeat;
           background-size:100% 100%;

        }
        .payform{
                    background-color:rgba(0,0,0,0.3);
                    height:450px;
                }
         .white
         {
            color:white;
            }
    </style>
</head>
<body>
<h1 style="text-align:center;font-family:sans-seriff">Payment Gateway</h1>
<form action="book/" method="POST">
    {%csrf_token%}
    <div class="row">
    <div class="col-lg-6" style="background-color:rgba(256,256,256,0.4);height:450px;">
        <h3 style="text-align:center">Check Details</h3>
        <div class="col-lg-6">

        Train no   :<br/><input type="text" value="{{tno}}" readonly name="tno"><br/><br/>
    Train name :<br/><input type="text" value="{{tname}}" readonly name="tname"><br/><br/>
    From       :<br/><input type="text" value="{{src}}" readonly name="src"><br/><br/>
    To         :<br/><input type="text" value="{{des}}" readonly name="des"><br/><br/>

    </div>
    <div class="col-lg-6">
    Class      :<br/><input type="text" value="{{cls}}" readonly name="cls"><br/><br/>
    No of Seats:<br/><input type="text" value="{{nos}}" readonly name="nos"><br/><br/>
    Date       :<br/><input type="text" value="{{dt}}" readonly name="date"><br/><br/>
    Total Price:<br/><input type="text" value="{{price}}" readonly name="price"><br/>
    </div>

    </div>
    <div class="col-lg-6 payform">
        <h3 style="text-align:center">Payment Method</h3>
    <select id="selectMe" name="select">
      <option value="option1">Credit or Debit card</option>
      <option value="option2">Paytm</option>

    </select>
       <div id="option1" class="group">
           <span class="white">Card Number:</span><br/>
           <input type="text" name="crd"><br/><br>
           <span class="white">Name on Card:</span><br/>
           <input type="text" name="nam"><br/><br/>
               <span class="white">CVV Number:</span><br/>
           <input type="password" maxlength="3" name="cvv"><br/><br/>
               <span class="white">Expiry:</span><br/>
           <input type="text" placeholder="MM/YY" name="exp"><br/><br/>



       </div>
       <div id="option2" class="group">
           <h3><span class="white">Click to proceed to Paytm Portal for payment</span></h3>
       </div>
    <input type="submit" value="Confirm Book" >
    </div>
        </div>
</form>
 <script>
    $(document).ready(function () {
  $('.group').hide();
  $('#option1').show();
  $('#selectMe').change(function () {
    $('.group').hide();
    $('#'+$(this).val()).show();
  })
});
</script>
</body>
</html>

home/templates/home/payment.html
{% extends './srbase.html' %}
{% block body %}
{% load static %}
   <style>
        body
        {
            height:650px;
           background-image:url('{% static "images/pay.jpg"%}');
           background-repeat:no-repeat;
           background-size:100% 100%;

        }
        .payform{
                    background-color:rgba(0,0,0,0.3);
                    height:450px;
                }
         .white
         {
            color:white;
            }
    </style>

<h1 style="text-align:center;font-family:sans-seriff">Payment Gateway</h1>

<h3 style="color:yellow;">from payment.html</h3>
<form action="book/" method="POST">
    {%csrf_token%}
    <div class="row">
    <div class="col-lg-6" style="background-color:rgba(256,256,256,0.4);height:450px;">
        <h3 style="text-align:center">Check Details</h3>
        <div class="col-lg-6">

        Train no   :<br/><input type="text" value="{{tno}}" readonly name="tno"><br/><br/>
    Train name :<br/><input type="text" value="{{tname}}" readonly name="tname"><br/><br/>
    From       :<br/><input type="text" value="{{src}}" readonly name="src"><br/><br/>
    To         :<br/><input type="text" value="{{des}}" readonly name="des"><br/><br/>

    </div>
    <div class="col-lg-6">
    Class      :<br/><input type="text" value="{{cls}}" readonly name="cls"><br/><br/>
    No of Seats:<br/><input type="text" value="{{nos}}" readonly name="nos"><br/><br/>
    Date       :<br/><input type="text" value="{{dt}}" readonly name="date"><br/><br/>
    Total Price:<br/><input type="text" value="{{price}}" readonly name="price"><br/>
    </div>

    </div>
    <div class="col-lg-6 payform">
        <h3 style="text-align:center">Payment Method</h3>
    <select id="selectMe" name="select">
      <option value="option1">Credit or Debit card</option>
      <option value="option2">Paytm</option>

    </select>
       <div id="option1" class="group">
           <span class="white">Card Number:</span><br/>
           <input type="text" name="crd"><br/><br>
           <span class="white">Name on Card:</span><br/>
           <input type="text" name="nam"><br/><br/>
               <span class="white">CVV Number:</span><br/>
           <input type="password" maxlength="3" name="cvv"><br/><br/>
               <span class="white">Expiry:</span><br/>
           <input type="text" placeholder="MM/YY" name="exp"><br/><br/>



       </div>
       <div id="option2" class="group">
           <h3><span class="white">Click to proceed to Paytm Portal for payment</span></h3>
       </div>
    <input type="submit" value="Confirm Book" >
    </div>
        </div>
</form>
 <script>
    $(document).ready(function () {
  $('.group').hide();
  $('#option1').show();
  $('#selectMe').change(function () {
    $('.group').hide();
    $('#'+$(this).val()).show();
  })
});
</script>
{% endblock %}

home/templates/home/pnr.html
{% extends './srbase.html' %}
{% block body %} 
      
    {% load static %}
    <title>PNR NUMBER</title>
    
        body{
            background-image:url('{% static "images/number.jpg"%}');
            background-size:100%;
            background-repeat:no-repeat;
        }
        h2 {
            color: red;
        }
        .sty
        {
            font-family: 'Arial';
            color:white;
        }
        .hd
        {
            margin-left:400px;
            }
         .tform{
            background-color:rgba(0,0,0,0.3);
            }
            .fpnr
            {
                width:20%;
                margin-left:500px;
                margin-top:150px;
                padding:15px;
                background-color:rgba(0,0,0,0.3);                
                }

        .tick{
            width:20%;
            height:150px;
            background-image:url('{% static "images/ticket6"%}');
            background-size:100% 100%;
            background-repeat:no-repeat;
            }
    </style>
<h2 style="color:red;">    GET TRAINS </h2>

<h3 style="color:yellow;">from pnr.html</h3>
{%if r%}
<h2 style="text-align:center"> Current PNR Status</h2>
<div class="fpnr">
{%for i in r%}

    <h4 class="sty">PNR-{{i.pnr}}<br/>
    NO of seats-{{i.nos}}<br/>
    Status-{{i.status}}<br/><br/></h4>

{%endfor%}
        <a href="{%url 'home:hom'%}"><button class="btn btn-success">Back To Homepage</button></a>

</div>
{%else%}
<h1 style="text-align:center;font-family:sans seriff; color: yellow; background-color: green; opacity: 70%; ">ENTER PNR NUMBER</h1>

<form class="fpnr" action="" method="POST" style="background-color: green; opacity: 70%;">
    {%csrf_token%}
    <span class="sty">PASSENGER NAME RECORD: </span><input type="text" name="pnr" required=""><br/><br/>
    <center><input type="submit" class="btn btn-primary" value="Check"></center>
</form>
{%endif%}
{% endblock %}

home/templates/home/trinfo.html
{% extends 'home/srbase.html' %}
{% block body %}

<h3 style="color:yellow;">from trinfo.html</h3>
<h2 style="text-align:center;"><span class="sty" style="font-size:50px;color:Yellow;">Train Schedule</span></h2>

    <table style="margin:100px 500px;font-size:30px;color:black;" class="table-striped table-bordered table-hover">
        <tr class="sty" style="color:black;padding:10px;">
           <th style="padding:10px;">Station ID</th>

            <th style="padding:10px;">Arrival Time</th>
        </tr>

    {% for i in data %}
        <tr>
            <td><h4>{{i.sid}}</h4> </td>
            <td><h4>{{i.atime}}</h4></td>
        </tr>

    {% endfor %}

    </table>
    <a href="{%url 'home:hom'%}" style="margin-left:550px"><button class="btn btn-primary">Back To Homepage</button></a>
{% endblock%}